# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Master.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cMaster.proto\x12\x03rpc\"\x18\n\x07Request\x12\r\n\x05index\x18\x01 \x01(\t\"\n\n\x08Response2k\n\rMasterService\x12*\n\tMasterMap\x12\x0c.rpc.Request\x1a\r.rpc.Response\"\x00\x12.\n\rMasterReducer\x12\x0c.rpc.Request\x1a\r.rpc.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Master_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=21
  _REQUEST._serialized_end=45
  _RESPONSE._serialized_start=47
  _RESPONSE._serialized_end=57
  _MASTERSERVICE._serialized_start=59
  _MASTERSERVICE._serialized_end=166
# @@protoc_insertion_point(module_scope)
