# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x03rpc\"\x19\n\x07Request\x12\x0e\n\x06status\x18\x01 \x01(\t\"\n\n\x08Response2g\n\x06Master\x12-\n\x0emapperFinished\x12\x0c.rpc.Request\x1a\r.rpc.Response\x12.\n\x0freducerFinished\x12\x0c.rpc.Request\x1a\r.rpc.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=21
  _REQUEST._serialized_end=46
  _RESPONSE._serialized_start=48
  _RESPONSE._serialized_end=58
  _MASTER._serialized_start=60
  _MASTER._serialized_end=163
# @@protoc_insertion_point(module_scope)
