# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.worker = channel.unary_unary(
                '/rpc.Master/worker',
                request_serializer=master__pb2.ClientRequest.SerializeToString,
                response_deserializer=master__pb2.Response.FromString,
                )
        self.mapperFinished = channel.unary_unary(
                '/rpc.Master/mapperFinished',
                request_serializer=master__pb2.Request.SerializeToString,
                response_deserializer=master__pb2.Response.FromString,
                )
        self.reducerFinished = channel.unary_unary(
                '/rpc.Master/reducerFinished',
                request_serializer=master__pb2.Request.SerializeToString,
                response_deserializer=master__pb2.Response.FromString,
                )


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def worker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mapperFinished(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reducerFinished(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'worker': grpc.unary_unary_rpc_method_handler(
                    servicer.worker,
                    request_deserializer=master__pb2.ClientRequest.FromString,
                    response_serializer=master__pb2.Response.SerializeToString,
            ),
            'mapperFinished': grpc.unary_unary_rpc_method_handler(
                    servicer.mapperFinished,
                    request_deserializer=master__pb2.Request.FromString,
                    response_serializer=master__pb2.Response.SerializeToString,
            ),
            'reducerFinished': grpc.unary_unary_rpc_method_handler(
                    servicer.reducerFinished,
                    request_deserializer=master__pb2.Request.FromString,
                    response_serializer=master__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.Master/worker',
            master__pb2.ClientRequest.SerializeToString,
            master__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mapperFinished(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.Master/mapperFinished',
            master__pb2.Request.SerializeToString,
            master__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reducerFinished(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.Master/reducerFinished',
            master__pb2.Request.SerializeToString,
            master__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
